import Head from 'next/head'
import style from '@/styles/Home.module.css'
import Link from 'next/link'

type Item = {
  id: number
  category: string
  image: string
  param: string
}

type Menu = Array<Item>

type Prop = {
  menu: Menu
}

export default function Home({ menu } : Prop) {
  return (
    <>
      <Head>
        <title>cookie ko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cookie.svg" />
      </Head>
      <div className={style.home}>
        <main className={style.grid}>
          {
            menu.map((item : Item) => {
              return (
                <Link key={item.category} href={item.param}>
                <div className={style.card}>
                  <div className={style.image}>
                    <img src={item.image} alt={item.category} />
                  </div>
                  <h3 className={style.category}>{item.category}</h3>
                  <div className={style.select}>select</div>
                </div>
              </Link>
              )
            })
          }
        </main>
      </div>
    </>
  )
}

async function getMenu() : Promise<Menu> {
  const response = await fetch("https://api-jollibee-menu.vercel.app/menu")
  const { data } = await response.json()
  return data
}

export async function getStaticProps() {
  const menu: Menu = await getMenu()
  return {
    props: {
      menu
    }
  }
}
