import Head from 'next/head'
import style from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home({ menu } : any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.grid}>
        {
          menu.data.map( (item : any) => {
            return (
              <Link key={item.category} href={item.param}>
              <div className={style.card}>
                <div className={style.image}>
                  <img src={item.image} alt={item.category} />
                </div>
                <h3 className={style.category}>{item.category}</h3>
                <div className={style.select}>select</div>
              </div>
            </Link>
            )
          })
        }
      </main>
    </>
  )
}

export async function getStaticProps() {
  const response = await fetch("https://api-jollibee-menu.vercel.app/menu")
  return {
    props: {
      menu: await response.json()
    }
  }
}
